[package]
name = "bevy_bsp"
version = "0.1.0"
authors = ["Casper Rogild Storm", "tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
decoder = { path = "../decoder" }

anyhow = "1.0"
bevy = "0.5"
glam = "0.14"