[package]
name = "rg3d_bsp"
version = "0.1.0"
authors = ["Casper Rogild Storm", "tarkah <admin@tarkah.dev>"]
edition = "2018"

[dependencies]
decoder = { path = "../decoder" }

anyhow = "1.0"
glam = "0.14"
rayon = "1.5.1"
rg3d = "0.20.0"